"""second_tables

Revision ID: 2eefafc7aea9
Revises: 584101fef90c
Create Date: 2019-01-29 20:11:42.722208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2eefafc7aea9'
down_revision = '584101fef90c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'new')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('new', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
