"""xxxxxxxxxx

Revision ID: a0a54a907612
Revises: 2eefafc7aea9
Create Date: 2019-01-29 20:31:50.579557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0a54a907612'
down_revision = '2eefafc7aea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=64), nullable=True))
    op.drop_column('users', 'xxx')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('xxx', mysql.VARCHAR(length=10), nullable=False))
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
